# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: yumiaura.myCat
PackageVersion: 0.1.37
PackageLocale: en-US
Publisher: yumiaura
PackageName: myCat
PackageUrl: https://github.com/yumiaura/myCat
License: MIT CAT LICENSE (Meow-IT License)
LicenseUrl: https://github.com/yumiaura/myCat/blob/0.1.37/LICENSE.txt
ShortDescription: Tiny animated desktop pet cat
ManifestType: defaultLocale
ManifestVersion: 1.12.0
