# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: yumiaura.myCat
PackageVersion: 0.1.37
InstallerType: portable
Commands:
  - mycat
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/yumiaura/myCat/releases/download/0.1.37/mycat-windows-x64.exe
    InstallerSha256: 995546DA86B5E0D94B08713511B5B3551ECD249CF1B27BAF234B18AC26E5ABF4
ManifestType: installer
ManifestVersion: 1.12.0
